### ISSUE TITLE
HostManager: Research current status

### ISSUE THREAD

**Issue by Rebits** [wazuh/qa-system-framework#27]
| Base branch | 
| ---- |
| `system-test`|

### Description

In the development branch, we have implemented a comprehensive set of fundamental methods for system and E2E host handling within the HostManager class. This class plays a pivotal role in facilitating remote low-level operations on designated hosts by utilizing the provided inventory.

However, it is crucial to conduct a thorough assessment to determine whether additional methods should be incorporated to ensure complete support for all system tests. 

### To Do

- [x] Conduct research on the HostManager class and thoroughly document its methods
- [x] Identify and incorporate any necessary methods required to implement all proposed system tests

**Comment by Rebits** [comment]
### 29/05/2023

Meeting with @BelenValdivia about:
- Current System tests approach.
- Status of the `qa-system-framework` repository
- `HostManager` and `WazuhManager` classes

**Comment by BelenValdivia** [comment]
### 29/05/2023
- Set up a local environment (Manager and Agent) with vagrant
- Created custom inventory.yml using the vagrant VMs
- Tested host connections

```
belen@belen-VirtualBox:~/Repositories/qa-system-framework$ ansible all -m ping -i inventory.yml
manager1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
agent1 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "ping": "pong"
}
belen@belen-VirtualBox:~/Repositories/qa-system-framework$ python3
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from wazuh_qa_framework.system.host_manager import HostManager
>>> hm = HostManager('inventory.yml')
>>> hm.check_connection('agent1')
True
>>> hm.check_connection('manager1')
True
```

**Comment by BelenValdivia** [comment]
### 01/06/2023

- Applied requested changes in the pull request:
  - Added install and uninstall function
  - Added Windows support in the append_block_in_file() function
  - Added ansible_arguments in all new functions
