### ISSUE TITLE
Wazuh Handler: API calls

### ISSUE THREAD

**Issue by Rebits** [wazuh/qa-system-framework#30]
| Related Issue                                 |
| --------------------------------------------- |
| https://github.com/wazuh/qa-system-framework/issues/35 |

### Description

As specified in  https://github.com/wazuh/qa-system-framework/issues/35 is required to create some method for API call handling for `WazuhHandler` class

**Comment by juliamagan** [comment]
### Update 20/06/2023

After reviewing the different developments both in [wazuh-qa](https://github.com/wazuh/wazuh-qa) and in this repository, it has been decided to start from the current development in the `system-refactor` branch.

#### Objectives

- [ ] Check that all the current implementation is working as expected.
- [ ] Create functions for the most common API calls.

**Comment by juliamagan** [comment]
## Update 21/06/2023

The current API class is intended to run locally, so we are adding an object as an attribute of WazuhHandler, and we will create functions for the most used endpoints.

[This list](https://gist.github.com/juliamagan/f45e1197c9be13e7b7128fb6e600448d) has been created showing the endpoints that are currently being used in [wazuh-qa system tests](https://github.com/wazuh/wazuh-qa/tree/4.4/tests/system). We should implement all these endpoints plus those that we consider may be useful in the future.

**Comment by juliamagan** [comment]
## Update 22/06/2023

Working branch: [30-wazuh-handler-api-calls](https://github.com/wazuh/qa-system-framework/tree/30-wazuh-handler-api-calls)

It has been decided to implement in `WazuhAPI()` the currently used endpoints, and the test will call them when needed. Only those endpoints that can be useful in the environment, such as restarting agents, for example, will be implemented in `WazuhHandler()`.

Working on implementing the list of the previous comment.

**Comment by juliamagan** [comment]
## Update 23/06/2023:

Added the currently used endpoints and some additional useful ones. Also added to return more information when the result of the request is `Bad Request`.

**Comment by juliamagan** [comment]
### Update

Applied requested changes

**Comment by juliamagan** [comment]
### Update
Solved conflicts
