### ISSUE TITLE
Creation of common system tests fixtures

### ISSUE THREAD

**Issue by Rebits** [wazuh/qa-system-framework#32]
| Related Issue                                 |
| --------------------------------------------- |
| https://github.com/wazuh/qa-system-framework/issues/35 |

### Description

As specified in  https://github.com/wazuh/qa-system-framework/issues/35 is required to create some fixtures and basic configuration files in order to standardize system tests.

**Comment by davidjiglesias** [comment]
To be evaluated as part of Wazuh packages redesign tier 2
