### ISSUE TITLE
Creation of evidence gathering method in case of system test failure

### ISSUE THREAD

**Issue by Rebits** [wazuh/qa-system-framework#33]
| Related Issue                                 |
| --------------------------------------------- |
| https://github.com/wazuh/qa-system-framework/issues/35 |

### Description

As specified in  https://github.com/wazuh/qa-system-framework/issues/35, one of the problems in the current framework is that is really hard to determine why a test fails.
It is suggested to create a fixture that will allow indexing custom files to the report for each test and also support using a custom evidence function.

**Comment by davidjiglesias** [comment]
To be evaluated as part of Wazuh packages redesign tier 2
