### ISSUE TITLE
HostManager: Include method to run ansible playbook directly to a host

### ISSUE THREAD

**Issue by Rebits** [wazuh/qa-system-framework#37]
### Description

The HostManager class enables the execution of low-level tasks on remote hosts. It leverages the testinfra framework for performing these tasks remotely. However, it would be beneficial to introduce a new method that utilizes the ansible-runner module, allowing the direct execution of playbooks within the environment.

This additional method would greatly assist in migrating system tests for installation and upgrades to the new framework. Furthermore, it would prove invaluable for handling more intricate tasks whenever the tests demand it.

### Design

The proposed method can be defined as follows:
```
def run_playbook(playbook_path: str, str, extra_vars):
    runner = ansible_runner.run(
        playbook=playbook_path,
        inventory=self.inventory_path,
        extravars=extra_vars,
    )
    return runner.rc == 0
```

> **Note**: 
> The inventory used should be the one provided in the HostManager constructor.

> **Warning**:
> It may be necessary to implement a method that handles exceptions in case the playbook fails, enhancing the readability of the error messages.

**Comment by BelenValdivia** [comment]
### 31/05/2023

- Research about ansible_runner

**Comment by BelenValdivia** [comment]
05/06/2023
- Added function to run a playbook on a host:
  Tested on linux agent , manager and windows agent

**Comment by BelenValdivia** [comment]
06/06/2023

- Worked on function exceptions
- Created PR https://github.com/wazuh/qa-system-framework/pull/49

**Comment by BelenValdivia** [comment]
21/06/2023
- Added ansible runner object as a return of the function
-  Added ansible-runner as a dependency in `project.toml`  for `system_tests_launcher`
![image](https://github.com/wazuh/qa-system-framework/assets/26927338/efec2e3b-5fb5-4a7e-a64a-a91eef581f19)
