### ISSUE TITLE
HostManager: Include method to run a python script on a host

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/qa-system-framework#51]
### Description

The HostManager class enables the execution of low-level tasks on remote hosts. It leverages the test-infra framework for performing these tasks remotely. 
It would be beneficial to introduce a new method that runs a Python script on a host.

**Comment by BelenValdivia** [comment]
07/06/2023
- Research how to execute Python script with ansible

**Comment by BelenValdivia** [comment]
08/06/2023
- Test how to run script on windows with a playbook
- Created function to run a python script on Linux

**Comment by Rebits** [comment]
09/06/2023

Meeting with @BelenValdivia about issues encountered with the testinfra syntaxis while using the Ansible task script.
Currently, it appears that using `windows.ansible('script', 'script_python_testing.py executable=python', check=False)` solves the problem to some extent. However, we still need to conduct further research to ensure a comprehensive solution is in place.

**Comment by BelenValdivia** [comment]
Created PR https://github.com/wazuh/qa-system-framework/pull/53

**Comment by BelenValdivia** [comment]
04/07/2023
- Applied requested changes

**Comment by pro-akim** [comment]
# 11/07/23 Update
In communication with Belen, it was explained that it is required to add #!/usr/bin/env python3  or #!/usr/bin/env python to the script in order to make it work.
It will be retested.

**Comment by BelenValdivia** [comment]
- Tested in different hosts with the same script as Antonio and the function works. All the information in this [comment](https://github.com/wazuh/qa-system-framework/pull/53#issuecomment-1638703686)

**Comment by BelenValdivia** [comment]
- Checking requested changes

**Comment by BelenValdivia** [comment]
- On hold due to release testing

**Comment by BelenValdivia** [comment]
- Testing changes

**Comment by BelenValdivia** [comment]
- On hold due to release testing
