### ISSUE TITLE
WazuhHandler: Install and uninstall Wazuh manager

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/qa-system-framework#54]
Add functions that allow install and uninstall the Wazuh manager through the [official](https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html#wazuh-server-node-installation) package or from [packages.wazuh.com](http://packages.wazuh.com/)

**Comment by BelenValdivia** [comment]
13/06/2023
- Added function to install the official Wazuh manager following the [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html#wazuh-server-node-installation) 
    - Tested on CentOS
- Added function to uninstall manager following the [documentation](https://documentation.wazuh.com/current/user-manual/uninstall/central-components.html#uninstall-the-wazuh-server)
  - Tested on CentOS

**Comment by BelenValdivia** [comment]
14/06/2023
- Install official wazuh manager function on Ubuntu:
  - I had problems running the command with ansible due to "|" is not recognized :
    ```    
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
    ```

**Comment by davidjiglesias** [comment]
To be evaluated as part of Wazuh packages redesign tier 2
