### ISSUE TITLE
Wazuh Handler: Install and uninstall Wazuh agent

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/qa-system-framework#55]
Add functions that allow install and uninstall the Wazuh manager through the [official](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html#add-the-wazuh-repository) package or from [packages.wazuh.com](http://packages.wazuh.com/)

**Comment by pro-akim** [comment]
# 13/07/2023
Starting research about how to approach install and uninstall Wazuh agent in hosts.

**Comment by pro-akim** [comment]
# Update
Leaving in hold the issue to move to https://github.com/wazuh/wazuh-qa/issues/3476 (higher priority)

**Comment by pro-akim** [comment]
## Update
Moved on hold due to higher priority tasks.

**Comment by pro-akim** [comment]
## Update
Method for installation and uninstallation of agents on Windows systems and APT created. A dialogue space should be generated to discuss which additional systems to include.

Moved to blocked until the discussion.

**Comment by pro-akim** [comment]
## Update
In light of higher-priority issues and the lack of progress on this one, it is being left unassigned in the backlog.

**Comment by davidjiglesias** [comment]
To be evaluated as part of Wazuh packages redesign tier 2
