### ISSUE TITLE
Wazuh Handler: Create, delete assign and unassign groups to agents

### ISSUE THREAD

**Issue by pro-akim** [wazuh/qa-system-framework#60]
# Description

## Develop for qa-system-framework in WazuhHandler

- Method to create and delete groups.
_It should include: via API, via CMD, via deleting or creating a directory, if it is possible.
Consider a method to create and delete groups individually, as well as create and delete groups through a list of groups._

- Method to assign and unassign agents to groups:
_It should include: via API, via CMD, via deleting or creating a directory, if it is possible.
It should include assigning and unassigning agents to groups individually, as well as receiving a list of agents for a group._

## Created methods
- #### wazuh_handler.create_group()
method: cmd/api
- #### wazuh_handler.delete_group()
method: cmd/api/folder
- #### wazuh_handler.assign_agent_group()
method: cmd/api
- #### wazuh_handler.assign_agents_group()
method: cmd/api
- #### wazuh_handler.unassign_agent_group()
method: api
- #### wazuh_handler.unassign_agents_group()
method: api
- #### wazuh_handler,check_agent_groups()
 method: cmd

**Comment by pro-akim** [comment]
## 28/06/2023

After developing methods, PR was done.
Some methods does not have API or Folder method.

**Comment by pro-akim** [comment]
# Update
Checking review.

**Comment by pro-akim** [comment]
# Update
Most of the fixes were performed. However, it will be needed to have some team communication in order to define 'validations' in each method.

**Comment by pro-akim** [comment]
# Update
Parameters successfully added, Tests OK
Ready to review

**Comment by pro-akim** [comment]
# Update
Changes are done, but Linter is not working properly, the last commit was just a linting correction but the message is wrong.
Ready to review

**Comment by pro-akim** [comment]
# Update
Moved to on hold for task with higher priorities

**Comment by pro-akim** [comment]
# Update 
Moved to on hold for task with higher priorities

**Comment by pro-akim** [comment]
# Update
Moved to on hold for task with higher priorities

**Comment by pro-akim** [comment]
# Update
Moved to on hold for task with higher priorities

**Comment by pro-akim** [comment]
## Update
Some small changes done after linter (replacement of " for ') and parameters of get_agents_id method

**Comment by pro-akim** [comment]
## Update
Some small changes were done after linter (replacement of " for ') and parameters of 'get_agents_id' method and 'get_agent_id', documentation fixed.

**Comment by pro-akim** [comment]
## Update
Some small changes were done after linter (replacement of " for ') and parameters of 'get_agents_id' method and 'get_agent_id', documentation fixed.

**Comment by Rebits** [comment]
Delayed ETA to 22. To allow a proper review

**Comment by pro-akim** [comment]
## Update
Fixes done after review.

**Comment by davidjiglesias** [comment]
LGTM!
