### ISSUE TITLE
Wazuh Handler: Stop agent/s ungracefully

### ISSUE THREAD

**Issue by pro-akim** [wazuh/qa-system-framework#61]
# Description

## Develop for qa-system-framework in WazuhHandler

- Add to stop_agent a parameter that allows ungracefully stop an agent.
- Add to stop_agents a parameter that allows ungracefully stop agents through a list of agents.
_The latter should consider the use of multithreading methods._

**Comment by pro-akim** [comment]
## 28/06/2023

Methods stop_agent and stop_agents were changed adding a parameter "type" where default option is "gracefully", but it is possible to do it ungracefully

**Comment by pro-akim** [comment]
## 06/07/2023
Retesting was initiated but put on hold due to higher priority tasks (workload testing in release).

**Comment by pro-akim** [comment]
# 13/07/2023 Update
Review checked, Starting fixes.

**Comment by pro-akim** [comment]
# 13/07/2023 Update
Changes done.
Starting with tests before pending review.

**Comment by pro-akim** [comment]
# 13/07/2023 Update
Test performed OK.
Changing to pending review.

**Comment by pro-akim** [comment]
# Update
Starting fixes after Review

**Comment by pro-akim** [comment]
# Update
Moved to pending review.
Changes done

**Comment by pro-akim** [comment]
## Update
Conflicts were solved.

**Comment by Rebits** [comment]
Delayed ETA to 22, in order to allow a review of the applied changes

**Comment by pro-akim** [comment]
## Update
Required changes done

**Comment by davidjiglesias** [comment]
LGTM!
