### ISSUE TITLE
Wazuh Handler: WazuhDB queries a socket

### ISSUE THREAD

**Issue by pro-akim** [wazuh/qa-system-framework#62]
# Description

## Develop for qa-system-framework in WazuhHandler

- Create a method to perform queries on wazuhdb through a socket.

**Comment by pro-akim** [comment]
## 29/06/2023
It will be convenient to scale over of https://github.com/wazuh/qa-system-framework/pull/53
Using it, It will be important to define a directory where .py files will be stored to be used.

**Comment by pro-akim** [comment]
## 05/07/2023
Pipelines are not working, it will remain on on-hold.

**Comment by pro-akim** [comment]
## Update
In light of higher-priority issues and the lack of progress on this one, it is being left unassigned in the backlog.

**Comment by davidjiglesias** [comment]
To be evaluated as part of Wazuh packages redesign tier 2
