### ISSUE TITLE
Wazuh Handler: Rules and decoders configuration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/qa-system-framework#66]
| Related issue |
|:--:|
| #35 |

## Description

It is necessary to create methods to be able to handle rules and decoders. These may require adding rules to a `local_rules.xml` file or adding rules files directly. The same applies to decoders.

> **Note**: In this first development, we will focus on the everyday use of rules and decoders of a user, so it will not be necessary to modify the default rules.

## Objectives

- [x] Add rules to `local_rules.xml`
- [x] Add decoders to `local_decoders.xml`
- [x] Add rules files
- [x] Add decoders files

**Comment by pro-akim** [comment]
# 12/07/2023 Update
All changes were done. 
Add and Change decoders were changed by create decoders
Same for rules.

## Tests:


### Evidences

Running:
<details>

1. wh.create_rule('manager1', '/home/akim/Desktop/decoder_total.xml', '/var/ossec/etc/decoders/local_decoder.xml', overwrite=True)

2. wh.create_rule('manager1', '/home/akim/Desktop/decoder_simple.xml', '/var/ossec/etc/decoders/local_decoder.xml', overwrite=False)

3. wh.create_rule('manager1', '/home/akim/Desktop/rule_total.xml', '/var/ossec/etc/rules/local_rules.xml', overwrite=True)

4. wh.create_rule('manager1', '/home/akim/Desktop/rule_simple.xml', '/var/ossec/etc/rules/local_rules.xml', overwrite=False)

</details>

Results:
<details>

1.  /var/ossec/etc/decoders/local_decoder.xml changed by /home/akim/Desktop/decoder_total.xml 

2.  /home/akim/Desktop/decoder_simple.xml added to /var/ossec/etc/decoders/local_decoder.xml 

3.  /var/ossec/etc/rules/local_rules.xml changed by /home/akim/Desktop/rule_total.xml 

4. /home/akim/Desktop/rule_simple.xml added to /var/ossec/etc/rules/local_rules.xml 


</details>

**Comment by pro-akim** [comment]
# 13/07/2023 Update

The linter is not functioning properly.
Even though line 891 is not present in https://github.com/wazuh/qa-system-framework/pull/73/commits/72ccf45c34e3e7e43337e04cb1f018ae41ed1402, the linter is still detecting a whitespace error. Therefore, a new pull request will be submitted for review, even if the linting error persists.

**Comment by pro-akim** [comment]
# 13/07/2023 Update

The linter is not functioning properly.
Even though line 891 is not present in https://github.com/wazuh/qa-system-framework/pull/73/commits/72ccf45c34e3e7e43337e04cb1f018ae41ed1402, the linter is still detecting a whitespace error. Therefore, a new pull request will be submitted for review, even if the linting error persists.

**Comment by davidjiglesias** [comment]
LGTM!
