### ISSUE TITLE
Wazuh Handler: Paths reorganization

### ISSUE THREAD

**Issue by juliamagan** [wazuh/qa-system-framework#74]
## Description

Currently, we can find `path` in the `global_variables` module, which contains the `WazuhPath` class and then, classes for each type of path (configuration, logs, binaries, etc.).

However, this is intended for integration tests, which run where Wazuh is installed, but as we are refactoring this framework for system and E2E tests, it will not work, as they do not run on the same node.

It may be interesting to consider that the inventory returns directly the installation path, whether it is the default or custom.

**Comment by davidjiglesias** [comment]
To be evaluated as part of Wazuh packages redesign tier 2
