### ISSUE TITLE
Wazuh Handler: Extend the request endpoints configuration

### ISSUE THREAD

**Issue by roronoasins** [wazuh/qa-system-framework#75]
# Description
Currently, we are able to perform request to WazuhAPI using the url, header, payload, and verify.

It will be useful adding an `Endpoint` class that allow us to fully customize the endpoints with `Authorizations`, `Query Parameters`, `Path Parameters`, `Responses`, `Request Body schema`, etc. This also happens with responses, like `message` and `Response Schema`.

If additional class isn't necessary, we need to extend the current classes to be able to include this.

**Comment by davidjiglesias** [comment]
To be evaluated as part of Wazuh packages redesign tier 2
